In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [79]:
x=pd.read_csv("Diabetes_XTrain.csv")
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              7      168             88             42      321  38.2   
1              8      110             76              0        0  27.8   
2              7      147             76              0        0  39.4   
3              2      100             66             20       90  32.9   
4              4      129             86             20      270  35.1   
..           ...      ...            ...            ...      ...   ...   
571            2      111             60              0        0  26.2   
572            7      187             68             39      304  37.7   
573            2      122             60             18      106  29.8   
574            4      154             72             29      126  31.3   
575            1       88             78             29       76  32.0   

     DiabetesPedigreeFunction  Age  
0                       0.787   40  
1                       0.237   58  
2                       0.257   43  
3                       0.867   28  
4                       0.231   23  
..                        ...  ...  
571                     0.343   23  
572                     0.254   41  
573                     0.717   22  
574                     0.338   37  
575                     0.365   29  

[576 rows x 8 columns]

In [80]:
for i in x.columns.values:
    m=x[i].mean()
    for j in range(len(x[i])):
        if x[i][j]==0:
            x[i][j]=m
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              7      168             88             42      321  38.2   
1              8      110             76             20       76  27.8   
2              7      147             76             20       76  39.4   
3              2      100             66             20       90  32.9   
4              4      129             86             20      270  35.1   
..           ...      ...            ...            ...      ...   ...   
571            2      111             60             20       76  26.2   
572            7      187             68             39      304  37.7   
573            2      122             60             18      106  29.8   
574            4      154             72             29      126  31.3   
575            1       88             78             29       76  32.0   

     DiabetesPedigreeFunction  Age  
0                       0.787   40  
1                       0.237   58  
2                       0.257   43  
3                       0.867   28  
4                       0.231   23  
..                        ...  ...  
571                     0.343   23  
572                     0.254   41  
573                     0.717   22  
574                     0.338   37  
575                     0.365   29  

[576 rows x 8 columns]

In [81]:
x=x.values
xtrain=x[:460]
xtest=x[460:]
print(xtrain.shape)
print(xtest.shape)

(460, 8)
(116, 8)


In [82]:
y=pd.read_csv("Diabetes_YTrain.csv")
y=y.values
ytrain=y[:460]
ytest=y[460:]
print(ytrain.shape)
print(ytest.shape)

(460, 1)
(116, 1)


In [83]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

def knn(X,Y,querypoint,k=5):
    vals=[]
    m=X.shape[0]
    for i in range(m):
        d=dist(querypoint,X[i])
        vals.append((d,Y[i]))
        
    vals=sorted(vals)
    vals=vals[:k]
    vals=np.array(vals)
    new_vals=np.unique(vals[:,1],return_counts=True)
    index=new_vals[1].argmax()
    fin=new_vals[0][index]
    return fin


In [84]:
c=0
for i in range(len(xtest)):
    ans=knn(xtrain,ytrain,xtest[i])
    if ans==ytest[i]:
        c+=1
print(c/116*100)

68.96551724137932


In [85]:
xval=pd.read_csv("Diabetes_Xtest.csv")
xval=xval.values
l=[]
for i in range(len(xval)):
    ans=knn(xtrain,ytrain,xval[i])
    l.append(ans)


In [86]:
l

[array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], 

In [87]:
outdf=pd.DataFrame(l,columns=["Outcome"])
outdf.to_csv("out.csv",index=False)